import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className="w-full min-h-screen bg-blue-300">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
    </div>
  );
}
